name: Somyaranjan Portfolio ->Build-Deploy to Main
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@main
      - run: npm install
      - run: npm run build
      - uses: jakejarvis/s3-sync-action@v1.0.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_S3_PROD_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
          SOURCE_DIR: "dist" # optional: defaults to entire repository
